### ISSUE TITLE
Python script not running in processing

### ISSUE THREAD

**Issue by wedgevic** [Code-Bullet/Storm-The-House-Auto-Clicker#1]
first of all, it wants for me to create a folder for each script and then it says:

processing.app.SketchException: ImportError: No module named numpy
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:242)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)

Thanks in advance,
Daniel

**Comment by lNyc** [comment]
you need to install the dependencies of the script such as numpy, PIL and opencv.

- https://pypi.org/project/numpy
- https://pypi.org/project/PIL/
- https://pypi.org/project/opencv-python/

But i'm not sure that they are the only packages you need to install.
